spring:
  data:
    mongodb:
      #uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: '10'
        minimum-idle: '5'
        pool-name: HikariPoolPrimary
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc-url: ${MYSQL_DATASOURCE_URI}
      username: ${MYSQL_DATASOURCE_APP_USERNAME}
      password: ${MYSQL_DATASOURCE_APP_PASSWORD}
    secondary:
      jdbc-url: ${REPORT_MYSQL_DATASOURCE_URI}
      username: ${REPORT_MYSQL_DATASOURCE_APP_USERNAME}
      password: ${REPORT_MYSQL_DATASOURCE_APP_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: '10'
        minimum-idle: '5'
        pool-name: HikariPoolSecondary
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari:
      #maximum-pool-size: '10'
      #minimum-idle: '5'
    #rl: ${MYSQL_DATASOURCE_URI}
    #username: ${MYSQL_DATASOURCE_APP_USERNAME}
    #password: ${MYSQL_DATASOURCE_APP_PASSWORD}
  flyway:
    enabled: 'false'
    baseline-on-migrate: 'true'
    #    out-of-order: 'true'
    url: ${MYSQL_DATASOURCE_URI}
    user: ${MYSQL_DATASOURCE_FLYWAY_USERNAME}
    password: ${MYSQL_DATASOURCE_FLYWAY_PASSWORD}
    locations: classpath:db/migration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  config:
    import: optional:file:.env[.properties]

app:
  cors-allowed-origins: *
  serviceTag: ${SERVICE_TAG:capital}
  secret: ${APP_JWT_SECRET:testabcd}
  verification:
    otp:
      request-limit: 4
      failure-limit: 3
  cache:
    password-expiry-in-minutes: 30
    sr-token-expiry-in-hours: 120
  crypto:
    encryption:
      rsa:
        enabled: false
      aes:
        key: 'secret-key-12345'
  external:
    sinfini:
      enabled: true
      baseUri: ${SINFINI_BASE_URI:http://alerts.sinfini.com/api/v3/index.php}
      apiKey: ${SINFINI_API_KEY:Afa8f859f3f8af5f9bd92c9e8db94bd39}
      sms:
        method: ${SINFING_SMS_METHOD:sms}
        sender: ${SINFINI_SMS_SENDER:SHPRKT}
        templateId: ${SINFINI_SMS_TEMPLATE_ID:1107159921248118728}
    kaleyra:
      enabled: true
      baseUri: ${KALEYRA_BASE_URI:https://api.kaleyra.io/v1}
      senderId: ${KALEYRA_SENDER_ID:HXIN1724808889IN}
      apiKey: ${KALEYRA_API_KEY:Aca6d903762f7aa22e3b1d392059be7cd}
      fromNo: ${KALEYRA_FROM_NO:917217894979}
      endpoints:
        send-messages: "/messages"
      whatsapp:
        otp-template-name: ${KALEYRA_WHATSAPP_OTP_TEMPLATE_NAME:o2_verification}
        channel: ${KALEYRA_WHATSAPP_CHANNEL:whatsapp}
        callBackUri: ${KALEYRA_CALL_BACK_URL:https://apiv2.shiprocket.in/v1/webhook/whatsapp}
    netcore:
      enabled: true
      baseUri: ${NETCORE_BASE_URI:https://emailapi.netcorecloud.net}
      apiKey: ${NETCORE_API_KEY:f8fb86901e186aa15a07e22a3de6b022}
      fromEmail: "info@mail.shiprocket.in"
      fromName: "Shiprocket"
      endpoints:
        send-mail: "/v5.1/mail/send"
    authmaster:
      baseUri: ${AUTHMASTER_BASE_URI:https://authmaster-staging.kartrocket.in}
      secret: ${AUTHMASTER_SERVICE_SECRET:1bae94ab67ad47dec2d3f8b965137c37}
      populate-resources:
        endpoint: ${AUTHMASTER_POPULATE_RESOURCES_ENDPOINT:/permission/populate}
        enabled: false

    shiprocket:
      api:
        baseUrl: ${SHIPROCKET_API_BASE_URL:https://qa-api-1.kartrocket.com}
        endpoints:
          kyc-details: /v1/settings/kyc/is-selfie-enable
          user-details-api-token: "/v1/external/omuni2/auth/user-details"
          user-details-internal-token: "/v1/auth/login/user"
      auth:
        baseUrl: ${SHIPROCKET_AUTH_BASE_URL:https://sr-auth-qa-1.kartrocket.com}
        endpoints:
          validate-token: /authorize/user
    klub:
      vendor-token: ${KLUB_VENDOR_TOKEN:test}
      vendor-code: ${KLUB_VENDOR_CODE:test}

aws:
  region: ${AWS_REGION:test}
  s3:
    bucketName: ${CAPITAL_BUCKET_NAME:test}
  cdn:
    url: ${CDN_URL:https://o2stage-capital-cdn.kartrocket.in}

redis:
  config: redisson-dev.yaml
fileUpload:
  coolOffWindowInMinutes: ${FILE_UPLOAD_COOLOFF_WINDOW:60}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
  health:
    redis:
      enabled: false  




####################################### KARZA API #############################################
external:
  karza:
    enabled: false
    vendor-token: ${KARZA_VENDOR_TOKEN:test}
    vendor-code: ${KARZA_VENDOR_CODE:test}
    api:
      endpoint:
        cross:
          verify:
            pancard:
              gst:
                url: /v3/tasks/async/verify_with_source/pan_gst_link
              aadhaar:
                url: /v3/tasks/async/verify_with_source/pan_aadhaar_link
        verify:
          gst:
            otp-url: /gst/uat/v2/gst-return-auth-advance
          aadhaar:
            url: /v3/tasks/async/verify_with_source/aadhaar_lite
          pancard:
            url: /v3/tasks/async/verify_with_source/ind_pan
          bank:
            proof:
              url: /v3/tasks/async/verify_with_source/validate_bank_account
        extract:
          pancard:
            url: /v3/tasks/sync/extract/ind_pan
          aadhaar:
            url: /v3/tasks/sync/extract/ind_aadhaar
          gst:
            url: /gst/uat/v2/gst-return-auth-advance
            pan:
              url: /gst/uat/v2/search
          bank:
            proof:
              url: /v3/tasks/sync/extract/ind_cheque
        compare:
          name:
            url: /v3/tasks/sync/compare/ind_names
      key: 423714eb-ece1-495b-8760-c2bf9ca3bf08
    verify:
      retry:
        backoff:
          millis: '300'
        max:
          attempts: '3'
    account:
      id: 6b00817c0377/2798d29c-763c-4b83-a4a9-3f28ea6f39a5
    base:
      uri: https://api.karza.in
    async:
      api:
        endpoint:
          tasks: /v3/tasks
karza:
  async:
    response:
      aadhaar:
        rely:
          'on':
            pan:
              aadhaar: 'true'
allowed:
  compare:
    name:
      score: '2'

encryption:
  key: ${ENCRYPTION_KEY:test}


