spring:
  data:
    mongodb:
      #uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: '10'
        minimum-idle: '5'
        pool-name: HikariPoolPrimary
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc-url: ${MYSQL_DATASOURCE_URI}
      username: ${MYSQL_DATASOURCE_APP_USERNAME}
      password: ${MYSQL_DATASOURCE_APP_PASSWORD}
    secondary:
      jdbc-url: ${REPORT_MYSQL_DATASOURCE_URI}
      username: ${REPORT_MYSQL_DATASOURCE_APP_USERNAME}
      password: ${REPORT_MYSQL_DATASOURCE_APP_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: '10'
        minimum-idle: '5'
        pool-name: HikariPoolSecondary
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari:
      #maximum-pool-size: '10'
      #minimum-idle: '5'
    #rl: ${MYSQL_DATASOURCE_URI}
    #username: ${MYSQL_DATASOURCE_APP_USERNAME}
    #password: ${MYSQL_DATASOURCE_APP_PASSWORD}
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
    #    out-of-order: 'true'
    url: ${MYSQL_DATASOURCE_URI}
    user: ${MYSQL_DATASOURCE_FLYWAY_USERNAME}
    password: ${MYSQL_DATASOURCE_FLYWAY_PASSWORD}
    locations: classpath:db/migration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  config:
    import: optional:file:.env[.properties]

app:
  captcha-verification:
    enabled: true
  cors-allowed-origins: https://qa-web-1.kartrocket.com,https://multichannel-appstore-qa.kartrocket.com,http://localhost:5371,http://app.shiprocket.local,https://app.shiprocket.in
  serviceTag: ${SERVICE_TAG:capital}
  secret: ${APP_JWT_SECRET:testabcd}
  web-url: ${WEB_URL:https://multichannel-appstore-qa.kartrocket.com/capital/home}
  verification:
    otp:
      request-limit: 4
      failure-limit: 3
  cache:
    password-expiry-in-minutes: 30
    sr-token-expiry-in-hours: 120
  crypto:
    encryption:
      rsa:
        enabled: false
      aes:
        key: 'secret-key-12345'
  external:
    sinfini:
      enabled: true
      baseUri: ${SINFINI_BASE_URI:http://alerts.sinfini.com/api/v3/index.php}
      apiKey: ${SINFINI_API_KEY}
      sms:
        method: ${SINFING_SMS_METHOD:sms}
        sender: ${SINFINI_SMS_SENDER:SHPRKT}
        templateId: ${SINFINI_SMS_TEMPLATE_ID:1107159921248118728}
    kaleyra:
      enabled: false
      baseUri: ${KALEYRA_BASE_URI:https://api.kaleyra.io/v1}
      senderId: ${KALEYRA_SENDER_ID}
      apiKey: ${KALEYRA_API_KEY}
      fromNo: ${KALEYRA_FROM_NO}
      endpoints:
        send-messages: "/messages"
      whatsapp:
        otp-template-name: ${KALEYRA_WHATSAPP_OTP_TEMPLATE_NAME:sr_capital_code}
        channel: ${KALEYRA_WHATSAPP_CHANNEL:whatsapp}
        callBackUri: ${KALEYRA_CALL_BACK_URL:https://capital-qa-1.kartrocket.com/api/v1/external/wa/webhook?secret-key=669dfe82d4490f4cf9f27c10}
        lead-not-connected-template-name: seller_notconnected_capital
        seller-thanks-template-name: thanks_seller_captial
    netcore:
      enabled: true
      baseUri: ${NETCORE_BASE_URI:https://emailapi.netcorecloud.net}
      apiKey: ${NETCORE_API_KEY:f8fb86901e186aa15a07e22a3de6b022}
      fromEmail: "info@mail.shiprocket.in"
      fromName: "Shiprocket"
      endpoints:
        send-mail: "/v5.1/mail/send"
    authmaster:
      baseUri: ${AUTHMASTER_BASE_URI:https://authmaster-staging.kartrocket.in}
      secret: ${AUTHMASTER_SERVICE_SECRET:1bae94ab67ad47dec2d3f8b965137c37}
      populate-resources:
        endpoint: ${AUTHMASTER_POPULATE_RESOURCES_ENDPOINT:/permission/populate}
        enabled: false

    shiprocket:
      api:
        baseUrl: ${SHIPROCKET_API_BASE_URL:https://qa-api-1.kartrocket.com}
        endpoints:
          kyc-details: /v1/settings/kyc/is-selfie-enable
          user-details-api-token: "/v1/external/omuni2/auth/user-details"
          user-details-internal-token: "/v1/auth/login/user"
      auth:
        baseUrl: ${SHIPROCKET_AUTH_BASE_URL:https://sr-auth-qa-1.kartrocket.com}
        endpoints:
          validate-token: /authorize/user
    klub:
      vendor-token: ${KLUB_VENDOR_TOKEN:test}
      vendor-code: ${KLUB_VENDOR_CODE:test}
    common:
      vendor-token: ${COMMON_VENDOR_TOKEN:661f14a7-9fbc-4f07-8f18-2917065d80}
      vendor-code: ${COMMON_VENDOR_CODE:8908f14a7-9fbc-4f07-3f18-2917063B8c}
    flexi:
      vendor-token: ${FLEXI_VENDOR_TOKEN}
      vendor-code: ${FLEXI_VENDOR_CODE}
      redirection-url: ${FLEXI_REDIRECTION_URL:https://ops.flexiloans.com/sanction/accept/%s}

aws:
  region: ${AWS_REGION:test}
  s3:
    bucketName: ${CAPITAL_BUCKET_NAME:test}
  cdn:
    url: ${CDN_URL:https://o2stage-capital-cdn.kartrocket.in}

redis:
  config: redisson-dev.yaml
fileUpload:
  coolOffWindowInMinutes: ${FILE_UPLOAD_COOLOFF_WINDOW:60}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
  health:
    redis:
      enabled: false  




####################################### KARZA API #############################################
external:
  google:
    baseUri: https://www.google.com
    captcha-secret-key: ${CAPTCHA_VALIDATION_SECRET_KEY:6LcPP7cqAAAAACUvJnEkjG9wGhVsQV1cVLcBJXx1}
    endpoints:
      captcha-site-verify: /recaptcha/api/siteverify
  karza:
    enabled: false
    vendor-token: ${KARZA_VENDOR_TOKEN:test}
    vendor-code: ${KARZA_VENDOR_CODE:test}
    api:
      endpoint:
        cross:
          verify:
            pancard:
              gst:
                url: /v3/tasks/async/verify_with_source/pan_gst_link
              aadhaar:
                url: /v3/tasks/async/verify_with_source/pan_aadhaar_link
        verify:
          gst:
            otp-url: /gst/uat/v2/gst-return-auth-advance
          aadhaar:
            url: /v3/tasks/async/verify_with_source/aadhaar_lite
          pancard:
            url: /v3/tasks/async/verify_with_source/ind_pan
          bank:
            proof:
              url: /v3/tasks/async/verify_with_source/validate_bank_account
        extract:
          pancard:
            url: /v3/tasks/sync/extract/ind_pan
          aadhaar:
            url: /v3/tasks/sync/extract/ind_aadhaar
          gst:
            url: /gst/uat/v2/gst-return-auth-advance
            pan:
              url: /gst/uat/v2/search
          itr:
            url: /itr/prod/v1/itr-return-forms
          bank:
            proof:
              url: /v3/tasks/sync/extract/ind_cheque
        compare:
          name:
            url: /v3/tasks/sync/compare/ind_names
      key: 423714eb-ece1-495b-8760-c2bf9ca3bf08
    verify:
      retry:
        backoff:
          millis: '300'
        max:
          attempts: '3'
    account:
      id: 6b00817c0377/2798d29c-763c-4b83-a4a9-3f28ea6f39a5
    base:
      uri: https://api.karza.in
    async:
      api:
        endpoint:
          tasks: /v3/tasks
  crif:
    enabled: true
    vendor-token: ${CRIF_VENDOR_TOKEN:test}
    vendor-code: ${CRIF_VENDOR_CODE:test}
    api:
      endpoint:
        extract:
          stage1:
            url: /Inquiry/do.getSecureService/DTC/initiate
          stage2:
            url: /Inquiry/do.getSecureService/DTC/response
      key: 423714eb-ece1-495b-8760-c2bf9ca3bf08
    public:
      company-id: -67891012345
      user-id: -678910
    verify:
      retry:
        backoff:
          millis: '300'
        max:
          attempts: '3'
    account:
      id: 6b00817c0377/2798d29c-763c-4b83-a4a9-3f28ea6f39a5
    base:
      uri: https://test.crifhighmark.com
    access-code:
      user: ${CRIF_USER}
      password: ${CRIF_PASSWORD}
      company-Name: ${CRIF_COMPANY_NAME}
      customer-id: ${CRIF_CUSTOMER_ID}
      app-id: ${CRIF_APP_ID}
      product-code: ${CRIF_PRODUCT_CODE}
karza:
  async:
    response:
      aadhaar:
        rely:
          'on':
            pan:
              aadhaar: 'true'
allowed:
  compare:
    name:
      score: '2'

encryption:
  key: ${ENCRYPTION_KEY:dev-testing}

kafka:
  basePath: KAFKA_BASE_PATH
  topics:
    statusUpdate: capital
  producer:
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    numberOfProducers: 1
    maxBlockTimeMs: 5000
    retrylock: capital-write-publisher-lock
    confluentUserName: ${CONFLUENT_USER_NAME:""}
    confluentPassword: ${CONFLUENT_PASSWORD:""}
    confluentEnabled: ${CONFLUENT_ENABLED:true}
  consumer:
    serviceName: capital
    bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    podPreDestroyGraceTimeInMs: ${KAFKA_PRE_POD_DESTROY_GRACE_MS:10000}
    confluentUserName: ${CONFLUENT_USER_NAME:""}
    confluentPassword: ${CONFLUENT_PASSWORD:""}
    confluentEnabled: ${CONFLUENT_ENABLED:true}
    retryTopicConsumerCount: 0
    mainConsumerCron: 0 0 */6 * * ?
    groups:
      - topicName: capital
        consumerCount: 1
        groupId: status-update
        topicHandler: status-update-handler
        commitBlockTimeMs: 5000
        handlerTimeoutMs: 25000
        groupingEnabled: false
        shouldPublishRetriesToSameTopic: true
        retryTopicConsumerCount: 0
        maxAttempts: 2
        syncRetry:
          maxRetry: 1
          retryIntervalMs: 1000

jobs:
  disbursement:
    cronInMinutes: 300
  sanction:
    cronInMinutes: 400
  status:
    cronInMinutes: 120
  communication:
    scheduledTime: 0 0 1 * * ?
  crif:
    purge:
      scheduledTime: 0 */5 * * * ?
      expireAt: 5 MINUTES

aes:
  secret:
    key: ${AES_SECRET_KEY}
  iv:
    key: ${AES_IV_KEY}

is:
  error-mail-trigger:
    enabled: ${IS_ERROR_MAIL_ENABLED:true}
  encryption:
    enabled: ${IS_ENCRYPTION_ENABLED:true}

error:
  email:
    recipientName: ${ERROR_EMAIL_RECIPIENT_NAME:vikas.sinwar@shiprocket.com,akhilesh.kumar@shiprocket.com}

server:
  tomcat:
    max-http-header-size: 8192


bypass:
  apis:
    "/api/public/crif/generate-otp":
      method:
        - POST
      captchaEnabled: true
      captchaAction: "GenerateAction"
    "/api/public/crif/verify-otp":
      method:
        - POST
      captchaEnabled: true
      captchaAction: "VerifyAction"
    "/api/public/crif/validate":
      method:
        - POST
      captchaEnabled: true
      captchaAction: "ValidateAction"
    "/api/public/crif/purge":
      method:
        - POST
      captchaEnabled: true
      captchaAction: "PurgeAction"
    "/api/public/crif/get-doc-type":
      method:
        - GET
      captchaEnabled: true
      captchaAction: "FetchDocTypeAction"
    "/api/public/crif/resend-otp":
      method:
        - POST
      captchaEnabled: true
      captchaAction: "ReSendOtpAction"
    "/api/public/crif/banners":
      method:
        - GET
      captchaEnabled: true
      captchaAction: "FetchBannerAction"

global:
  loan-vendor-id: 1