spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: ${REDIS_DATABASE}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    timeout: ${REDIS_CONNECTION_TIMEOUT}
    useSsl: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    show-sql: 'false'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '10'
      minimum-idle: '5'
    url: ${MYSQL_DATASOURCE_URI}
    username: ${MYSQL_DATASOURCE_APP_USERNAME}
    password: ${MYSQL_DATASOURCE_APP_PASSWORD}
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
    #    out-of-order: 'true'
    url: ${MYSQL_DATASOURCE_URI}
    user: ${MYSQL_DATASOURCE_FLYWAY_USERNAME}
    password: ${MYSQL_DATASOURCE_FLYWAY_PASSWORD}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration