package com.sr.capital.helpers.enums;

public enum LeadStatus {
    PENDING("pending"),
    LEAD_START("lead start"),
    NOT_CONNECTED("Not connected"),
    CALL_CONNECTED("call connected"),
    NOT_INTERESTED("Not Interested"),
    INTERESTED_DOCUMENT_PENDING("Seller Interested Document Pending"),
    INTERESTED_DOCUMENT_SUBMITTED("Seller Interested Document Submitted"),
    DOCUMENT_UNDER_CREDIT_EVALUTION("Document under credit evaluation"),
    LOAN_OFFER_NOT_GENERATED_BY_LENDER("loan offer not generated by lender"),
    REJECTED_BY_ONE_LP_REFERRED_TO_ANOTHER("rejcted by one lp and referred to another"),
    LOAN_OFFER_GENERATED("loan offer generated"),
    LOAN_OFFER_DECLINED_BY_SELLER("loan offer declined by seller"),
    LOAN_OFFER_ACCEPTED("loan offer accepted"),
    LOAN_OFFER_PARTIALLY_DISBURSED("loan offer partially disbursed"),
    LOAN_OFFER_FULLY_DISBURSED("loan offer fully disbursed");
    /*INTERESTED_FULLY_DISBURSED("Interested & Fully Disbursed")
    INTERESTED_FOLLOW_UP("Interested & Follow Up"),
    INTERESTED_REJECTED("Interested & Rejected"),
    INTERESTED_SANCTIONED("Interested & Sanctioned"),
    INTERESTED_SANCTIONED_NOT_DISBURSED("Interested & Sanctioned but Not Disbursed"),
    INTERESTED_SANCTIONED_NOT_FULLY_DISBURSED("Interested & Sanctioned but Not Fully Disbursed"),
    INTERESTED_FULLY_DISBURSED_AGAIN("Interested & Fully Disbursed"); // Duplicate removed*/

    private final String displayName;

    LeadStatus(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }

    public static void validateLeadStatus(LeadStatus status) throws IllegalArgumentException {
        switch (status) {
            case NOT_INTERESTED:
            case LOAN_OFFER_FULLY_DISBURSED:
            case LOAN_OFFER_DECLINED_BY_SELLER:
                throw new IllegalArgumentException("Invalid Lead Status: " + status);
            default:
                // Do nothing if the status is valid
        }
    }
}
