package com.sr.capital.helpers.enums;

public enum LoanStatus {
   PRE_APPROVED, PENDING,APPROVED,REJECTED,APPLICATION_SUBMITTED,DOCUMENT_REQUIRED, DOCUMENT_SUBMITTED,DOCUMENT_APPROVED,LOAN_OFFER_GENERATED,LOAN_OFFER_ACCEPTED,LOAN_OFFER_DECLINED,DISBURSED,REPAYMENT_IN_PROGRESS,
    OVERDUE,PAID_IN_FULL,CLOSED,CHARGED_OFF,DEDUPECHECK,DEDUPEREJECT,PRE_OFFER,APPLICATION_REJECTED,DOCUMENT_UPLOAD,APPLICATION_UNDER_REVIEW,OFFER_GENERATION,OFFER_REJECTED,KYC,APPLICATION_COMPLETED,AMOUNT_DISBURSED,APPLICATION_IN_PROGRESS;
}
