package com.sr.capital.helpers.enums;

public enum ProviderRequestTemplateType {

    VALIDATE_TOKEN,
    GET_TOKEN,
    CREATE_LEAD,
    GET_LOAN,
    VALIDATE_LOAN,

    UPLOAD_DOCUMENT,

    PENDING_DOCUMENT,

    LOAN__STATUS_WEBHOOK,

    FETCH_DISBURSED_DETAILS,

    FETCH_SANCTIONED_OFFER,

    ACCEPT_SECTION_OFFER,
    UPDATE_LEAD,
    FETCH_KFS,
    REJECT_OFFER,

    CRIF_STAGE_1,
    CRIF_STAGE_2,
    CRIF_STAGE_3;
}
